name: oms_dbt
version: 1.0.0
profile: oms_dbt

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

clean-targets:
  - target
  - dbt_packages

models:
  oms_dbt:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  oms_dbt:
    +schema: raw_seeds

snapshots:
  oms_dbt:
    +schema: snapshots
